# SPARTA AI Security Configuration
# This file defines security policies and configurations

version: "1.0"

# Security Headers
security_headers:
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "DENY"
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains"
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Permissions-Policy: "geolocation=(), microphone=(), camera=()"

# CORS Configuration
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Request-ID"
  expose_headers:
    - "X-Request-ID"
    - "X-Process-Time"
  allow_credentials: true
  max_age: 3600

# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_minute: 100
  requests_per_hour: 1000
  burst_size: 20
  
# File Upload Security
file_upload:
  max_size_mb: 100
  allowed_extensions:
    - ".csv"
    - ".xlsx"
    - ".xls"
    - ".json"
    - ".parquet"
    - ".tsv"
  blocked_extensions:
    - ".exe"
    - ".sh"
    - ".bat"
    - ".cmd"
    - ".ps1"
    - ".php"
    - ".jsp"
  scan_for_viruses: true
  quarantine_suspicious: true

# Code Execution Security
code_execution:
  enabled: true
  timeout_seconds: 30
  max_memory_mb: 512
  max_output_size_mb: 10
  allowed_imports:
    - "pandas"
    - "numpy"
    - "matplotlib"
    - "seaborn"
    - "plotly"
    - "scipy"
    - "sklearn"
  forbidden_imports:
    - "os"
    - "sys"
    - "subprocess"
    - "socket"
    - "requests"
    - "urllib"
  sandbox_enabled: true

# Authentication
authentication:
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  password_min_length: 8
  password_require_uppercase: true
  password_require_lowercase: true
  password_require_digit: true
  password_require_special: true
  max_login_attempts: 5
  lockout_duration_minutes: 15

# Logging
logging:
  level: "INFO"
  sanitize_sensitive_data: true
  mask_patterns:
    - "password"
    - "token"
    - "api_key"
    - "secret"
    - "credential"
  log_retention_days: 90
  audit_log_enabled: true

# Database Security
database:
  use_ssl: true
  connection_timeout: 30
  pool_size: 10
  max_overflow: 20
  echo_sql: false
  parameterized_queries_only: true

# API Security
api:
  require_https: true
  api_key_header: "X-API-Key"
  request_id_header: "X-Request-ID"
  max_request_size_mb: 10
  timeout_seconds: 60

# Monitoring & Alerts
monitoring:
  enabled: true
  alert_on_suspicious_activity: true
  alert_on_failed_logins: true
  alert_on_rate_limit_exceeded: true
  alert_email: "security@spartaai.com"

# Compliance
compliance:
  gdpr_enabled: true
  data_retention_days: 365
  allow_data_export: true
  allow_data_deletion: true
  privacy_policy_url: "https://spartaai.com/privacy"
  terms_of_service_url: "https://spartaai.com/terms"

# Vulnerability Scanning
vulnerability_scanning:
  enabled: true
  scan_dependencies: true
  scan_code: true
  scan_containers: true
  fail_on_high_severity: true
  fail_on_critical_severity: true

# Secrets Management
secrets:
  use_environment_variables: true
  use_vault: false
  rotate_secrets_days: 90
  never_log_secrets: true
  never_commit_secrets: true
