version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: sparta-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - sparta-net
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: sparta-frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sparta-net
    volumes:
      - ./frontend/public:/usr/share/nginx/html/public

  db:
    image: postgres:15-alpine
    container_name: sparta-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: sparta_db
      POSTGRES_USER: sparta
      POSTGRES_PASSWORD: sparta_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - sparta-net

  redis:
    image: redis:7-alpine
    container_name: sparta-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sparta-net

  prometheus:
    image: prom/prometheus:latest
    container_name: sparta-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sparta-net

  grafana:
    image: grafana/grafana:latest
    container_name: sparta-grafana
    ports:
      - "3000:3000"
    networks:
      - sparta-net
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  nginx:
    image: nginx:alpine
    container_name: sparta-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - sparta-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: sparta-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - sparta-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: sparta-logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logging/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - sparta-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: sparta-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - sparta-net

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  es_data:

networks:
  sparta-net:
    driver: bridge
