version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sparta
      POSTGRES_PASSWORD: sparta_pass
      POSTGRES_DB: sparta_test
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6380:6379"
