apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-backend-green
  labels:
    app: sparta-backend
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sparta-backend
      color: green
  template:
    metadata:
      labels:
        app: sparta-backend
        color: green
    spec:
      containers:
        - name: sparta-backend
          image: DOCKER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
