apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sparta-frontend
  template:
    metadata:
      labels:
        app: sparta-frontend
    spec:
      containers:
        - name: sparta-frontend
          image: DOCKER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
