name: CD - Staging

on:
  push:
    branches: [ develop ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    # Secrets are used only on steps that require them to reduce editor/schema warnings
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (optional)
        if: ${{ secrets.AWS_ROLE_TO_ASSUME != '' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'
      - name: Deploy to staging
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_STAGING }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          chmod +x infra/ci-scripts/deploy_staging.sh
          ./infra/ci-scripts/deploy_staging.sh
      - name: Run E2E tests (Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Playwright tests
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps
          npx playwright test --project=chromium --reporter=list
